In [1]:
import pandas as pd

In [2]:
movies=pd.read_csv(r"C:\Users\Dell\Documents\My ML Projects\Hybrid Recommendation System\data\movie.csv")
ratings=pd.read_csv(r"C:\Users\Dell\Documents\My ML Projects\Hybrid Recommendation System\data\rating.csv")

In [4]:
#take subset of users
sample_users = ratings['userId'].sample(5000,random_state=42)
ratings_sample=ratings[ratings['userId'].isin(sample_users)]

#Merge
df = ratings_sample.merge(movies, on = 'movieId')

df.shape

(2163296, 6)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2163296 entries, 0 to 2163295
Data columns (total 6 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  str
 4   title      str
 5   genres     str
dtypes: float64(1), int64(2), str(3)
memory usage: 99.0 MB

In [6]:
df.describe()

             userId       movieId        rating
count  2.163296e+06  2.163296e+06  2.163296e+06
mean   6.987951e+04  1.190358e+04  3.367813e+00
std    3.979944e+04  2.271551e+04  1.052473e+00
min    1.400000e+01  1.000000e+00  5.000000e-01
25%    3.505000e+04  1.259000e+03  3.000000e+00
50%    7.146700e+04  2.918000e+03  3.500000e+00
75%    1.046380e+05  6.286000e+03  4.000000e+00
max    1.384190e+05  1.310190e+05  5.000000e+00

In [7]:
df.shape

(2163296, 6)

**Preprocessing**

Keeping only useful columns

In [8]:
df = df[['userId', 'movieId', 'rating', 'title', 'genres']]

In [9]:
df.columns

Index(['userId', 'movieId', 'rating', 'title', 'genres'], dtype='str')

Remove Duplicates

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.shape

(2163296, 5)

Handling genres

In [12]:
df['genres'] = df['genres'].str.replace('|',' ')

In [13]:
df.head()

,userId,movieId,rating,title,genres
0,14,1,4.5,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,14,7,3.5,Sabrina (1995),Comedy Romance
2,14,17,5.0,Sense and Sensibility (1995),Drama Romance
3,14,34,3.0,Babe (1995),Children Drama
4,14,62,4.0,Mr. Holland's Opus (1995),Drama

Handle very rare movies

In [14]:
movie_counts = df['title'].value_counts()

df = df[df['title'].isin(movie_counts[movie_counts > 10].index)]

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 2128006 entries, 0 to 2163295
Data columns (total 5 columns):
 #   Column   Dtype
---  ------   -----
 0   userId   int64
 1   movieId  int64
 2   rating   float64
 3   title    str
 4   genres   str
dtypes: float64(1), int64(2), str(2)
memory usage: 97.4 MB

Remove duplicate movies for content based

In [16]:
movies_df = df[['movieId', 'title', 'genres']].drop_duplicates()

In [17]:
movies_df.shape

(10772, 3)

reset index

In [18]:
movies_df = movies_df.reset_index(drop=True)

In [20]:
movies_df.shape

(10772, 3)

Saving processed data

In [22]:
df.to_csv("C:/Users/Dell/Documents/My ML Projects/Hybrid Recommendation System/data/processed_ratings.csv", index=False)

In [23]:
movies_df.to_csv("C:/Users/Dell/Documents/My ML Projects/Hybrid Recommendation System/data/processed_movies.csv", index=False)